const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Firstname",
    labelFor: "firstname",
    id: "firstname",
    name: "firstname",
    type: "text",
    autoComplete: "firstname",
    isRequired: true,
    placeholder: "Firstname",
  },
  {
    labelText: "Lastname",
    labelFor: "lastname",
    id: "lastname",
    name: "lastname",
    type: "text",
    autoComplete: "lastname",
    isRequired: true,
    placeholder: "Lastname",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

const expenseCategoryFields = [
  {
    labelText: "Category Name",
    labelFor: "categoryname",
    id: "categoryname",
    name: "categoryname",
    type: "text",
    autoComplete: "categoryname",
    isRequired: true,
    placeholder: "Category Name",
  },
];

const expenseFields = [
  {
    labelText: "Expense Name",
    labelFor: "expensename",
    id: "expensename",
    name: "expensename",
    type: "text",
    autoComplete: "expensename",
    isRequired: true,
    placeholder: "Expense Name",
  },
  {
    labelText: "Category",
    labelFor: "category",
    id: "category",
    name: "category",
    type: "test",
    autoComplete: "category",
    isRequired: true,
    placeholder: "Category",
  },
  {
    labelText: "Amount",
    labelFor: "amount",
    id: "amount",
    name: "amount",
    type: "number",
    autoComplete: "amount",
    isRequired: true,
    placeholder: "Amount",
  },
  {
    labelText: "Payment Type",
    labelFor: "type",
    id: "type",
    name: "type",
    type: "text",
    autoComplete: "type",
    isRequired: true,
    placeholder: "Payment Type",
  },
];

export { loginFields, signupFields, expenseCategoryFields, expenseFields };
