const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Firstname",
    labelFor: "firstname",
    id: "firstname",
    name: "firstname",
    type: "text",
    autoComplete: "firstname",
    isRequired: true,
    placeholder: "Firstname",
  },
  {
    labelText: "Lastname",
    labelFor: "lastname",
    id: "lastname",
    name: "lastname",
    type: "text",
    autoComplete: "lastname",
    isRequired: true,
    placeholder: "Lastname",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

const expenseCategoryFields = [
  {
    labelText: "Category Name",
    labelFor: "categoryname",
    id: "categoryname",
    name: "categoryname",
    type: "text",
    autoComplete: "categoryname",
    isRequired: true,
    placeholder: "Category Name",
  },
];

const expenseFields = [
  {
    labelText: "Expense Name",
    labelFor: "expensename",
    id: "expensename",
    name: "expensename",
    type: "text",
    autoComplete: "expensename",
    isRequired: true,
    placeholder: "Expense Name",
  },
  {
    labelText: "Category",
    labelFor: "category",
    id: "category",
    name: "category",
    type: "test",
    autoComplete: "category",
    isRequired: true,
    placeholder: "Category",
  },
  {
    labelText: "Amount",
    labelFor: "amount",
    id: "amount",
    name: "amount",
    type: "number",
    autoComplete: "amount",
    isRequired: true,
    placeholder: "Amount",
  },
  {
    labelText: "Select Payment Date & Time",
    labelFor: "paymenttime",
    id: "paymenttime",
    name: "paymenttime",
    type: "text",
    autoComplete: "paymenttime",
    isRequired: true,
    placeholder: "Select Payment Date & Time",
  },
  {
    labelText: "Paid Through",
    labelFor: "paid_by",
    id: "paid_by",
    name: "paid_by",
    type: "text",
    autoComplete: "paid_by",
    isRequired: true,
    placeholder: "Paid Through",
  },
  {
    labelText: "Spend",
    labelFor: "spend",
    id: "spend",
    name: "spend",
    type: "text",
    autoComplete: "spend",
    isRequired: true,
    placeholder: "Spend",
  },
  {
    labelText: "Other details",
    labelFor: "otherdetails",
    id: "otherdetails",
    name: "otherdetails",
    type: "text",
    autoComplete: "otherdetails",
    isRequired: false,
    placeholder: "Other details",
  },
];

const groupFields = [
  {
    labelText: "Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
  },
  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Description",
  },
  {
    labelText: "Users",
    labelFor: "users",
    id: "users",
    name: "users",
    type: "text",
    autoComplete: "users",
    isRequired: true,
    placeholder: "Users",
  },
]

export { loginFields, signupFields, expenseCategoryFields, expenseFields, groupFields };
